export const P = {
  app: { fontFamily: "'IBM Plex Sans',sans-serif", background: "#0c0e12", minHeight: "100vh", color: "#e8eaed" },
  pg: { margin: "0 auto", padding: "0 18px 72px" },
  hdr: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "14px 18px", background: "#11141a", borderBottom: "1px solid rgba(255,255,255,.08)", marginBottom: 16, marginLeft: -18, marginRight: -18 },
  logo: { fontSize: 17, fontWeight: 600, display: "flex", alignItems: "center", gap: 10, letterSpacing: ".2px", color: "#e8eaed" },
  sub: { fontSize: 10, color: "#5f6672", marginTop: 1, fontFamily: "'JetBrains Mono',monospace", letterSpacing: ".5px" },
  iBtn: { background: "#1a1d24", border: "0.5px solid rgba(255,255,255,.08)", borderRadius: 6, padding: 8, color: "#8b919c", cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center" },
  warn: { display: "flex", alignItems: "center", gap: 8, background: "rgba(224,169,59,.08)", border: "1px solid rgba(224,169,59,.18)", borderRadius: 6, padding: "10px 12px", marginBottom: 14, margin: "0 18px 14px" },
  ws: { fontSize: 11, color: "#8b919c", marginTop: 1 },
  body: { },
  g2: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(180px, 1fr))", gap: 8, marginBottom: 12 },
  g3: { display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 10, marginBottom: 16 },
  act: { background: "#13161c", border: "0.5px solid rgba(255,255,255,.07)", borderRadius: 8, padding: "14px", display: "flex", flexDirection: "column", gap: 6, cursor: "pointer", alignItems: "flex-start" },
  aIc: { width: 36, height: 36, borderRadius: 6, background: "#15324a", color: "#4aa3df", display: "flex", alignItems: "center", justifyContent: "center" },
  aLb: { fontSize: 13, fontWeight: 500, color: "#e8eaed" },
  chips: { display: "flex", flexDirection: "column", gap: 12, marginBottom: 18 },
  chipGroup: { },
  chipGLabel: { fontSize: 11, fontWeight: 500, color: "#8b919c", marginBottom: 6, display: "flex", alignItems: "center", gap: 6, textTransform: "uppercase", letterSpacing: ".5px", fontFamily: "'JetBrains Mono',monospace" },
  chipRow: { display: "flex", flexWrap: "wrap", gap: 6 },
  chip: { background: "#13161c", border: "0.5px solid rgba(255,255,255,.07)", borderRadius: 6, padding: "5px 10px", fontSize: 11, display: "flex", alignItems: "center", gap: 6 },
  chN: { color: "#8b919c" }, chC: { color: "#4aa3df", fontFamily: "'JetBrains Mono',monospace", fontWeight: 500 },
  secT: { fontSize: 11, fontWeight: 500, color: "#8b919c", marginBottom: 10, textTransform: "uppercase", letterSpacing: ".5px", fontFamily: "'JetBrains Mono',monospace", display: "flex", alignItems: "center", gap: 8 },
  sCard: { display: "flex", justifyContent: "space-between", alignItems: "center", background: "#13161c", border: "0.5px solid rgba(255,255,255,.07)", borderRadius: 6, padding: "11px 14px", marginBottom: 6 },
  sN: { fontSize: 13, fontWeight: 500, color: "#e8eaed" }, sM: { fontSize: 11, color: "#5f6672", marginTop: 2, fontFamily: "'JetBrains Mono',monospace" },
  top: { display: "flex", alignItems: "center", gap: 10, padding: "14px 18px", background: "#11141a", borderBottom: "1px solid rgba(255,255,255,.08)", marginBottom: 16, marginLeft: -18, marginRight: -18 },
  bk: { background: "none", border: "none", color: "#4aa3df", display: "flex", alignItems: "center", gap: 3, fontSize: 12, cursor: "pointer", padding: 0 },
  pT: { fontSize: 15, fontWeight: 500, color: "#e8eaed" },
  ztabs: { display: "flex", flexDirection: "column", gap: 10, marginBottom: 14 },
  ztGroup: { },
  ztGLabel: { fontSize: 11, fontWeight: 500, color: "#8b919c", marginBottom: 6, display: "flex", alignItems: "center", gap: 6, textTransform: "uppercase", letterSpacing: ".5px", fontFamily: "'JetBrains Mono',monospace" },
  ztRow: { display: "flex", flexWrap: "wrap", gap: 5 },
  zt: { background: "#13161c", border: "0.5px solid rgba(255,255,255,.07)", borderRadius: 6, padding: "5px 10px", fontSize: 11, color: "#8b919c", cursor: "pointer", display: "flex", alignItems: "center", gap: 4 },
  ztOn: { background: "#15324a", border: "0.5px solid rgba(74,163,223,.4)", borderRadius: 6, padding: "5px 10px", fontSize: 11, color: "#4aa3df", cursor: "pointer", fontWeight: 500, display: "flex", alignItems: "center", gap: 4 },
  ztB: { fontSize: 9, background: "rgba(74,163,223,.2)", color: "#4aa3df", padding: "0 4px", borderRadius: 3, fontWeight: 500, fontFamily: "'JetBrains Mono',monospace" },
  subLabel: { fontSize: 10, color: "#5f6672", marginBottom: 3, marginTop: 6, fontFamily: "'JetBrains Mono',monospace", letterSpacing: ".3px" },
  upRow: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(160px, 1fr))", gap: 8, marginBottom: 12 },
  upC: { background: "#13161c", border: "0.5px solid rgba(255,255,255,.07)", borderRadius: 8, padding: "16px 8px", display: "flex", flexDirection: "column", alignItems: "center", gap: 6, cursor: "pointer" },
  upL: { fontSize: 11, fontWeight: 500, color: "#8b919c" },
  iGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill,minmax(90px,1fr))", gap: 5, marginBottom: 12 },
  thBox: { position: "relative", aspectRatio: "1", borderRadius: 6, overflow: "hidden" },
  th: { width: "100%", height: "100%", objectFit: "cover", cursor: "pointer", display: "block", borderRadius: 6, border: "0.5px solid rgba(255,255,255,.08)" },
  thDel: { position: "absolute", top: 2, right: 2, background: "rgba(0,0,0,.75)", border: "none", borderRadius: 4, padding: 2, color: "#e24b4a", cursor: "pointer" },
  thIdx: { position: "absolute", bottom: 2, left: 2, background: "rgba(0,0,0,.75)", color: "#8b919c", fontSize: 8, padding: "1px 4px", borderRadius: 3, fontFamily: "'JetBrains Mono',monospace" },
  thPg: { position: "absolute", top: 2, left: 2, background: "rgba(155,140,219,.8)", color: "#fff", fontSize: 7, padding: "1px 3px", borderRadius: 3 },
  thClip: { position: "absolute", top: 2, left: 2, fontSize: 9, background: "rgba(78,201,155,.8)", borderRadius: 3, padding: "0 2px" },
  thCap: { position: "absolute", bottom: 0, left: 0, right: 0, background: "rgba(0,0,0,.82)", color: "#e8eaed", fontSize: 8, padding: "2px 3px", lineHeight: 1.2, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  vDot: { position: "absolute", top: 2, right: 2, background: "rgba(74,163,223,.85)", borderRadius: "50%", width: 14, height: 14, display: "flex", alignItems: "center", justifyContent: "center", color: "#fff" },
  lb: { display: "block", fontSize: 10, fontWeight: 500, color: "#8b919c", marginBottom: 5, marginTop: 12, textTransform: "uppercase", letterSpacing: ".5px", fontFamily: "'JetBrains Mono',monospace" },
  inp: { width: "100%", background: "#13161c", border: "0.5px solid rgba(255,255,255,.1)", borderRadius: 6, padding: "10px 11px", fontSize: 13, color: "#e8eaed", outline: "none", fontFamily: "'IBM Plex Sans',sans-serif" },
  ht: { fontSize: 10, color: "#5f6672", marginTop: 4 },
  sel: { background: "#13161c", border: "0.5px solid rgba(255,255,255,.07)", borderRadius: 6, padding: "8px 9px", fontSize: 11, color: "#8b919c", cursor: "pointer", textAlign: "left" },
  selOn: { background: "#15324a", border: "0.5px solid rgba(74,163,223,.4)", borderRadius: 6, padding: "8px 9px", fontSize: 11, color: "#4aa3df", cursor: "pointer", fontWeight: 500, textAlign: "left" },
  grpLabel: { fontSize: 11, fontWeight: 500, color: "#8b919c", marginBottom: 5, textTransform: "uppercase", letterSpacing: ".5px", fontFamily: "'JetBrains Mono',monospace", display: "flex", alignItems: "center", gap: 6 },
  sq: { background: "#13161c", border: "0.5px solid rgba(255,255,255,.07)", borderRadius: 5, padding: "6px 12px", fontSize: 11, color: "#8b919c", cursor: "pointer", fontFamily: "'JetBrains Mono',monospace" },
  sqOn: { background: "#15324a", border: "0.5px solid rgba(74,163,223,.4)", borderRadius: 5, padding: "6px 12px", fontSize: 11, color: "#4aa3df", cursor: "pointer", fontWeight: 500, fontFamily: "'JetBrains Mono',monospace" },
  drop: { border: "1px dashed rgba(255,255,255,.12)", borderRadius: 8, padding: "22px 12px", textAlign: "center", cursor: "pointer", marginBottom: 12, background: "#0f1217" },
  refBx: { background: "#13161c", border: "0.5px solid rgba(155,140,219,.18)", borderRadius: 8, padding: 9, marginTop: 5, marginBottom: 3 },
  lnk: { background: "none", border: "none", color: "#4aa3df", fontSize: 11, cursor: "pointer", textDecoration: "underline", padding: 0 },
  mini: { width: 38, height: 38, objectFit: "cover", borderRadius: 4, border: "0.5px solid rgba(255,255,255,.08)", cursor: "pointer", flexShrink: 0 },
  more: { width: 38, height: 38, borderRadius: 4, background: "#1a1d24", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 10, color: "#5f6672", flexShrink: 0 },
  anaBtn: { width: "100%", background: "#1d6ea8", border: "none", borderRadius: 8, padding: 13, fontSize: 14, fontWeight: 500, color: "#fff", cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", gap: 7, fontFamily: "'IBM Plex Sans',sans-serif" },
  secBtn: { width: "100%", background: "#13161c", border: "0.5px solid rgba(155,140,219,.3)", borderRadius: 8, padding: 11, fontSize: 13, fontWeight: 500, color: "#9b8cdb", cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", gap: 6, fontFamily: "'IBM Plex Sans',sans-serif", marginBottom: 7 },
  spPan: { background: "#13161c", border: "0.5px solid rgba(255,255,255,.07)", borderRadius: 8, padding: 8, textAlign: "center" },
  spLb: { fontSize: 11, fontWeight: 500, color: "#8b919c", marginBottom: 6, textTransform: "uppercase", letterSpacing: ".3px", fontFamily: "'JetBrains Mono',monospace" },
  spImg: { width: "100%", maxHeight: "70vh", objectFit: "contain", borderRadius: 6, cursor: "pointer", border: "0.5px solid rgba(255,255,255,.06)" },
  spE: { height: 300, display: "flex", alignItems: "center", justifyContent: "center", color: "#3a3f47", fontSize: 12, background: "#0f1217", borderRadius: 6 },
  spNav: { display: "flex", alignItems: "center", justifyContent: "center", gap: 8, marginTop: 4 },
  nv: { background: "#1a1d24", border: "0.5px solid rgba(255,255,255,.08)", borderRadius: 5, padding: "4px 8px", color: "#8b919c", cursor: "pointer" },
  center: { display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", minHeight: "68vh", textAlign: "center" },
  pulse: { width: 80, height: 80, borderRadius: "50%", background: "#15324a", display: "flex", alignItems: "center", justifyContent: "center", animation: "pulse-ring 2s infinite", marginBottom: 18 },
  prB: { width: "78%", maxWidth: 260, height: 4, background: "#1a1d24", borderRadius: 2, overflow: "hidden", marginBottom: 8, marginLeft: "auto", marginRight: "auto" },
  prF: { height: "100%", background: "#4aa3df", borderRadius: 2, transition: "width .4s" },
  prT: { fontSize: 11, color: "#5f6672", fontFamily: "'JetBrains Mono',monospace" },
  resH: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", background: "#13161c", border: "0.5px solid rgba(255,255,255,.07)", borderRadius: 8, padding: "14px", marginBottom: 8 },
  bdLg: { fontSize: 11, fontWeight: 500, background: "#3a2e15", color: "#e0a93b", padding: "4px 10px", borderRadius: 4, whiteSpace: "nowrap", fontFamily: "'JetBrains Mono',monospace" },
  bdOk: { fontSize: 11, fontWeight: 500, background: "#15332a", color: "#4ec99b", padding: "4px 10px", borderRadius: 4, display: "flex", alignItems: "center", gap: 4, whiteSpace: "nowrap", fontFamily: "'JetBrains Mono',monospace" },
  rvBtn: { flex: 1, background: "#13161c", border: "0.5px solid rgba(155,140,219,.2)", borderRadius: 6, padding: "8px 10px", display: "flex", alignItems: "center", justifyContent: "center", gap: 5, cursor: "pointer", color: "#9b8cdb", fontSize: 12, fontWeight: 500, fontFamily: "'IBM Plex Sans',sans-serif" },
  repBtn: { flex: 1, background: "#13161c", border: "0.5px solid rgba(74,163,223,.2)", borderRadius: 6, padding: "10px 12px", display: "flex", alignItems: "center", justifyContent: "center", gap: 6, cursor: "pointer", color: "#4aa3df", fontSize: 12, fontWeight: 500, fontFamily: "'IBM Plex Sans',sans-serif" },
  sumC: { background: "#13161c", border: "0.5px solid rgba(155,140,219,.18)", borderRadius: 8, padding: 12, marginBottom: 8 },
  sumT: { fontSize: 11, fontWeight: 500, color: "#9b8cdb", textTransform: "uppercase", letterSpacing: ".5px", marginBottom: 5, fontFamily: "'JetBrains Mono',monospace" },
  sumTx: { fontSize: 13, lineHeight: 1.6, color: "#c4c9d0" },
  fCard: { background: "#13161c", border: "0.5px solid rgba(255,255,255,.07)", borderRadius: 8, padding: 12, marginBottom: 6 },
  disc: { display: "flex", alignItems: "flex-start", gap: 7, background: "#13161c", border: "0.5px solid rgba(255,255,255,.06)", borderRadius: 6, padding: "10px 12px", marginTop: 18 },
  ov: { position: "fixed", inset: 0, background: "rgba(0,0,0,.85)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 100, padding: 12 },
  pan: { background: "#13161c", border: "0.5px solid rgba(255,255,255,.1)", borderRadius: 10, padding: "22px 18px", width: "92%", maxWidth: 380 },
  panT: { fontSize: 15, fontWeight: 500, color: "#e8eaed", marginBottom: 10 },
  pri: { width: "100%", background: "#1d6ea8", border: "none", borderRadius: 6, padding: 10, fontSize: 13, fontWeight: 500, color: "#fff", cursor: "pointer", marginTop: 8, fontFamily: "'IBM Plex Sans',sans-serif", display: "flex", alignItems: "center", justifyContent: "center" },
  clX: { position: "absolute", top: -7, right: -7, background: "rgba(226,75,74,.85)", border: "none", borderRadius: "50%", width: 26, height: 26, display: "flex", alignItems: "center", justifyContent: "center", color: "#fff", cursor: "pointer", zIndex: 10 },
  pdfPan: { background: "#13161c", border: "0.5px solid rgba(255,255,255,.1)", borderRadius: 10, padding: 16, width: "95%", maxWidth: 900, maxHeight: "84vh", overflowY: "auto", position: "relative" },
  pdfCtrl: { display: "flex", flexWrap: "wrap", gap: 5, alignItems: "center", marginBottom: 8, padding: "6px 0", borderTop: "0.5px solid rgba(255,255,255,.06)", borderBottom: "0.5px solid rgba(255,255,255,.06)" },
  sm: { background: "#1a1d24", border: "0.5px solid rgba(255,255,255,.08)", borderRadius: 5, padding: "4px 8px", fontSize: 10, color: "#8b919c", cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", gap: 2 },
  rIn: { width: 38, background: "#1a1d24", border: "0.5px solid rgba(255,255,255,.08)", borderRadius: 4, padding: "3px 5px", fontSize: 10, color: "#e8eaed", textAlign: "center", outline: "none" },
  pdfG: { display: "grid", gridTemplateColumns: "repeat(auto-fill,minmax(100px,1fr))", gap: 6, marginBottom: 8 },
  pdfTh: { position: "relative", borderRadius: 6, overflow: "hidden", cursor: "pointer", transition: "border-color .15s" },
  pdfCh: { position: "absolute", top: 2, right: 2, background: "#4aa3df", borderRadius: "50%", width: 18, height: 18, display: "flex", alignItems: "center", justifyContent: "center", color: "#fff" },
  pdfN: { position: "absolute", bottom: 1, left: 1, background: "rgba(0,0,0,.7)", color: "#8b919c", fontSize: 8, padding: "0 3px", borderRadius: 2, fontFamily: "'JetBrains Mono',monospace" },
  refPan: { background: "#13161c", border: "0.5px solid rgba(255,255,255,.1)", borderRadius: 10, padding: 16, width: "95%", maxWidth: 800, maxHeight: "84vh", overflowY: "auto", position: "relative" },
  toast: { position: "fixed", bottom: 20, left: "50%", transform: "translateX(-50%)", background: "#1d6ea8", color: "#fff", padding: "8px 18px", borderRadius: 6, fontSize: 12, fontWeight: 500, zIndex: 200, boxShadow: "0 4px 16px rgba(0,0,0,.4)" },
};
